/**
 * Actions
 */
const LOGIN = 'LOGIN'
const LOGOUT = 'LOGOUT'
const VALID_SESSION = 'VALID_SESION'
const REFRESH_TOKEN = 'REFRESH_TOKEN'
const AUTO_LOGOUT = 'AUTO_LOGOUT'
const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

/**
 * Mutations
 */
const SET_TOKEN = 'SET_TOKEN'
const SET_REFRESH_TOKEN = 'SET_REFRESH_TOKEN'
const SET_EXPIRE_IN = 'SET_EXPIRE_IN'
const CLEAR_ACCOUNT_STATE = 'CLEAR_ACCOUNT_STORE'
const SET_USER = 'SET_USER'
const SET_ID = 'SET_ID'
const SET_ROLE = 'SET_ROLE'
const SET_BRANCH_OFFICE = 'SET_BRANCH_OFFICE'
const SET_TOKEN_TYPE = 'SET_TOKEN_TYPE'
const SET_TIME_OUT = 'SET_TIME_OUT'

/**
 * Getters
 */

const GET_TOKEN = 'GET_TOKEN'
const GET_ID = 'GET_ID'
const GET_USER = 'GET_USER'
const GET_ROLE = 'GET_ROLE'
const GET_BRANCH_OFFICE = 'GET_BRANCH_OFFICE'
const GET_TOKEN_TYPE = 'GET_TOKEN_TYPE'
const GET_REFRESH_TOKEN = 'GET_REFRESH_TOKEN'
/**
 * Actions Login
 * @type {Object}
 */
export const ACTIONS = {
  LOGIN,
  LOGOUT,
  VALID_SESSION,
  REFRESH_TOKEN,
  AUTO_LOGOUT,
  LOGIN_SUCCESS
}

/**
 * Muttations Lgin
 * @type {Object}
 */
export const MUTATIONS = {
  CLEAR_ACCOUNT_STATE,
  SET_TOKEN,
  SET_REFRESH_TOKEN,
  SET_USER,
  SET_EXPIRE_IN,
  SET_ID,
  SET_ROLE,
  SET_BRANCH_OFFICE,
  SET_TOKEN_TYPE,
  SET_TIME_OUT
}

export const GETTERS = {
  GET_TOKEN,
  GET_ID,
  GET_USER,
  GET_ROLE,
  GET_BRANCH_OFFICE,
  GET_TOKEN_TYPE,
  GET_REFRESH_TOKEN
}
